name: Type Check

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: "3.12"
      mypy-args:
        type: string
        default: "."

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv python install ${{ inputs.python-version }}

      - run: uv sync --group dev

      - run: uv run mypy ${{ inputs.mypy-args }}
